ALTER TABLE blog_posts
  ADD COLUMN IF NOT EXISTS content_blocks JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS seo_title TEXT,
  ADD COLUMN IF NOT EXISTS seo_description TEXT,
  ADD COLUMN IF NOT EXISTS canonical_url TEXT;

UPDATE blog_posts SET content_blocks = jsonb_build_array(jsonb_build_object('type', 'paragraph', 'text', content)) WHERE content_blocks = '[]'::jsonb AND content <> '';

INSERT INTO blog_posts (slug, title, excerpt, content, category, tags, author, published_at, featured_image, reading_time, featured, status, content_blocks, seo_title, seo_description)
VALUES
('power-bi-software-solution-pakistan', 'Power BI software solution in Pakistan for smarter operations', 'Modern reporting helps growing businesses move from scattered spreadsheets to confident decisions.', 'Power BI turns operational data into clear dashboards for faster decisions.', 'Software', ARRAY['Analytics','Power BI','Reporting'], 'BlueChip Team', '2026-07-10', '/images/blog/erp-reporting.svg', '5 min read', true, 'published', '[{"type":"paragraph","text":"Power BI turns operational data into clear dashboards for faster decisions."},{"type":"h2","text":"Make reporting part of the daily rhythm"},{"type":"bullet-list","items":["Connect sales and operational data.","Give teams a shared view of performance.","Turn recurring questions into useful dashboards."]}]'::jsonb, 'Power BI software solution in Pakistan for smarter operations', 'Discover how reporting and analytics help businesses gain visibility.'),
('restaurant-pos-system-pakistan', 'How to choose the right restaurant POS system in Pakistan', 'A strong restaurant POS combines speed, reporting, and flexibility.', 'The right POS helps teams move quickly from order intake to payment and reporting.', 'POS', ARRAY['POS','Restaurant','Operations'], 'BlueChip Team', '2026-06-24', '/images/blog/pos-inventory-control.svg', '4 min read', false, 'published', '[{"type":"paragraph","text":"The right POS helps teams move quickly from order intake to payment and reporting."},{"type":"h2","text":"Choose for the busiest shift"},{"type":"numbered-list","items":["Test order speed and kitchen routing.","Review inventory and reporting workflows.","Confirm training and support plans."]}]'::jsonb, 'How to choose the right restaurant POS system in Pakistan', 'What to look for in a restaurant POS that supports operations.'),
('fbr-digital-invoicing-guide', 'A practical guide to FBR digital invoicing for businesses', 'Build an invoice workflow that supports compliance without avoidable manual effort.', 'Digital invoicing works best when finance, sales, and technology teams share one process.', 'Compliance', ARRAY['FBR','Finance','Digital Invoicing'], 'BlueChip Team', '2026-05-18', '/images/blog/digital-invoicing.svg', '6 min read', false, 'published', '[{"type":"paragraph","text":"Digital invoicing works best when finance, sales, and technology teams share one process."},{"type":"h2","text":"Prepare the workflow before integration"},{"type":"bullet-list","items":["Review invoice data and approvals.","Connect finance and operational systems.","Keep records ready for review."]}]'::jsonb, 'A practical guide to FBR digital invoicing for businesses', 'Practical digital invoicing workflow guidance for businesses.'),
('erp-systems-future-trends-pakistan', 'Future trends in ERP systems shaping business growth', 'Modern ERP systems are moving toward connected data and flexible workflows.', 'ERP platforms continue to evolve as businesses want faster access to reliable information.', 'ERP', ARRAY['ERP','Automation','Strategy'], 'BlueChip Team', '2026-04-02', '/images/blog/erp-data-foundation.svg', '5 min read', false, 'published', '[{"type":"paragraph","text":"ERP platforms continue to evolve as businesses want faster access to reliable information."},{"type":"h2","text":"The connected ERP direction"},{"type":"bullet-list","items":["Shared operational data.","Flexible workflows.","Accessible reporting."]}]'::jsonb, 'Future trends in ERP systems shaping business growth', 'Explore the trends defining the next generation of ERP systems.'),
('erp-benefits-and-challenges', 'Understanding the benefits and challenges of ERP systems', 'A well-planned ERP rollout improves visibility but requires clear ownership.', 'ERP systems can transform daily operations when implemented with a clear plan.', 'ERP', ARRAY['ERP','Change Management','Implementation'], 'BlueChip Team', '2026-03-12', '/images/blog/software-implementation.svg', '4 min read', false, 'published', '[{"type":"paragraph","text":"ERP systems can transform daily operations when implemented with a clear plan."},{"type":"h2","text":"Balance capability with adoption"},{"type":"callout","tone":"info","title":"Plan for the people","text":"Training, ownership, and support are as important as configuration."}]'::jsonb, 'Understanding the benefits and challenges of ERP systems', 'Learn how ERP improves operational visibility and what implementation requires.'),
('seo-that-supports-sales', 'SEO that supports sales teams instead of vanity metrics', 'Connect search intent to the questions buyers ask before you contact you.', 'SEO creates business value when it helps the right people find useful answers.', 'SEO', ARRAY['SEO','Content','Growth'], 'BlueChip Team', '2026-03-01', '/images/blog/seo-sales-alignment.svg', '5 min read', false, 'published', '[{"type":"paragraph","text":"SEO creates business value when it helps the right people find useful answers."},{"type":"h2","text":"Connect content to commercial questions"},{"type":"bullet-list","items":["Start with customer problems.","Add proof that makes the next step safe.","Link guidance to a clear next action."]}]'::jsonb, 'SEO that supports sales teams instead of vanity metrics', 'SEO planning that connects useful content and qualified enquiries.'),
('ai-assisted-customer-operations', 'Where AI assistance fits into customer operations', 'Use AI to reduce repetitive work while keeping human judgement at the centre.', 'AI is most useful when it removes friction from repeatable work without hiding important decisions.', 'AI', ARRAY['AI','Customer Service','Automation'], 'BlueChip Team', '2026-02-18', '/images/blog/ai-customer-operations.svg', '6 min read', false, 'published', '[{"type":"paragraph","text":"AI is most useful when it removes friction from repeatable work without hiding important decisions."},{"type":"h2","text":"A safe starting sequence"},{"type":"numbered-list","items":["Choose a narrow workflow.","Set approved information and boundaries.","Keep human review for customer-impacting actions.","Review errors regularly."]}]'::jsonb, 'Where AI assistance fits into customer operations', 'A practical guide to introducing AI assistance with human oversight.'),
('software-implementation-without-disruption', 'How to implement new business software without disrupting the day', 'A phased implementation protects the workflows that keep the business moving.', 'Software implementation is an operational change programme, not just an installation task.', 'Software', ARRAY['Software','Implementation','Change'], 'BlueChip Team', '2026-02-04', '/images/blog/software-implementation.svg', '5 min read', false, 'published', '[{"type":"paragraph","text":"Software implementation is an operational change programme, not just an installation task."},{"type":"h2","text":"Use a phased rollout"},{"type":"bullet-list","items":["Document the current process.","Pilot one team.","Train on real scenarios.","Expand after support questions become predictable."]}]'::jsonb, 'How to implement new business software without disrupting the day', 'A phased software implementation approach for growing teams.')
ON CONFLICT (slug) DO NOTHING;